<a href="https://colab.research.google.com/github/yaswanth-kumar546/BallCatcher-Game-/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

HERE I AM LEARNING NUMPY

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np

Numpy is a powerful library in Python that is used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are some basic concepts of Numpy:
1. Arrays: Numpy provides a powerful array object called ndarray, which is a multi-dimensional array that can hold elements of the same data type. It allows for efficient storage and manipulation of large datasets.

2. Vectorized Operations: Numpy allows for vectorized operations, which means that you can perform operations on entire arrays without the need for explicit loops. This leads to faster and more efficient code.

3. Broadcasting: Numpy supports broadcasting, which is a powerful mechanism that allows operations to be performed on arrays of different shapes and sizes. It automatically adjusts the shapes of the arrays to make them compatible for operations.

4. Universal Functions (ufuncs): Numpy provides a set of universal functions that operate element-wise on arrays. These functions are optimized for performance and can be applied to arrays of any shape.

5. Indexing and Slicing: Numpy allows for advanced indexing and slicing techniques to access and manipulate specific elements or subsets of an array. This includes boolean indexing, fancy indexing, and slicing with steps.

6. Linear Algebra: Numpy provides a comprehensive set of functions for linear algebra operations, including matrix multiplication, eigenvalues, singular value decomposition, and more.

7. Random Number Generation: Numpy includes a module for generating random numbers, which can be used for various applications such as simulations, data analysis, and machine learning.

8. Integration with Other Libraries: Numpy is often used in conjunction with other libraries such as Pandas, Matplotlib, and SciPy for data analysis, visualization, and scientific computing.

Overall, Numpy is a fundamental library for numerical computing in Python and is widely used in various fields such as data science, machine learning, and scientific research.

In [31]:
import numpy as np
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1[0])
print(arr1)

1D Array:
1
[1 2 3 4 5]


In [32]:
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)
print('shape of the array:', arr2.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
shape of the array: (2, 3)


In [8]:
# Create a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(arr3)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Perform element-wise addition
arr4 = arr1 + 10
print("\nElement-wise Addition:")
print(arr4)


Element-wise Addition:
[11 12 13 14 15]


In [10]:
# Perform element-wise multiplication
arr5 = arr1 * 2
print("\nElement-wise Multiplication:")
print(arr5)


Element-wise Multiplication:
[ 2  4  6  8 10]


In [11]:
# Perform matrix multiplication
arr6 = np.dot(arr2, arr2.T)
print("\nMatrix Multiplication:")
print(arr6)


Matrix Multiplication:
[[14 32]
 [32 77]]


In [14]:
# Perform broadcasting
arr2_compatible = np.array([[10, 20, 30, 40, 50], [100, 200, 300, 400, 500]])
arr7 = arr1 + arr2_compatible
print("\nBroadcasting:")
print(arr7)


Broadcasting:
[[ 11  22  33  44  55]
 [101 202 303 404 505]]


In [16]:
# Generate random numbers
random_arr = np.random.rand(3, 3)
print("\nRandom Array:")
print(random_arr)


Random Array:
[[0.61889376 0.6309941  0.0633188 ]
 [0.36465069 0.82699376 0.80224389]
 [0.64112452 0.67270248 0.8880801 ]]


In [29]:

import sys
#here we are creating list of 1000 integers
list_1000= np.arange(1000)
# print(list_1000)

#here we are creating numpy array of 1000 integers
array_1000 = np.arange(1000)
# print(array_1000)

# here again lets print size of the list and array in bytes
print(f"Size of list: {sys.getsizeof(list_1000)} bytes")
print(f"Size of array: {array_1000.nbytes}, bytes")

# lets take time to check here how long it takes to add list and array

import time

#sum the list
start_time = time.time()
sum_list=sum(list_1000)
end_time=time.time()
list_sum_time= (end_time-start_time) * 1000


# Sum the array
start_time=time.time()
sum_array=np.sum(array_1000)
end_time= time.time()
array_sum_time= (end_time-start_time) * 1000

# Now print the time it take to sum the list and array
print(f"Time to sum list: {list_sum_time:.2f} milliseconds")
print(f"Time to sum array: {array_sum_time: .2f} milliseconds")


Size of list: 8112 bytes
Size of array: 8000, bytes
Time to sum list: 0.30 milliseconds
Time to sum array:  0.21 milliseconds


In [30]:
# creating an array 0 to 9
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# data types in numpy
